import {
  AssistantChangedMessageSchema,
  AssistantCreateRequestSchema,
  AssistantCreateResponseSchema,
  AssistantDeleteRequestSchema,
  AssistantDeleteResponseSchema,
  AssistantListRequestSchema,
  AssistantListResponseSchema,
  AssistantUpdateRequestSchema,
  AssistantUpdateResponseSchema,
} from "./assistant/rpc-schemas.js";
import {
  LarkChannelApprovePairingRequestSchema,
  LarkChannelApprovePairingResponseSchema,
  LarkChannelApplyBotRequestSchema,
  LarkChannelApplyBotResponseSchema,
  LarkChannelConfigureRequestSchema,
  LarkChannelConfigureResponseSchema,
  LarkChannelDeleteBotRequestSchema,
  LarkChannelDeleteBotResponseSchema,
  LarkChannelGetBotApplicationRequestSchema,
  LarkChannelGetBotApplicationResponseSchema,
  LarkChannelGetStatusRequestSchema,
  LarkChannelGetStatusResponseSchema,
  LarkChannelRejectPairingRequestSchema,
  LarkChannelRejectPairingResponseSchema,
  LarkChannelRevokeUserRequestSchema,
  LarkChannelRevokeUserResponseSchema,
  LarkChannelSetEnabledRequestSchema,
  LarkChannelSetEnabledResponseSchema,
  LarkChannelStatusChangedMessageSchema,
  LarkChannelTestConnectionRequestSchema,
  LarkChannelTestConnectionResponseSchema,
} from "./channel/lark/rpc-schemas.js";
import {
  DaemonClientAccessApproveRequestSchema,
  DaemonClientAccessApproveResponseSchema,
  DaemonClientAccessDeleteRequestSchema,
  DaemonClientAccessDeleteResponseSchema,
  DaemonClientAccessHistoryDeleteRequestSchema,
  DaemonClientAccessHistoryDeleteResponseSchema,
  DaemonClientAccessListRequestSchema,
  DaemonClientAccessListResponseSchema,
  DaemonClientAccessSetPausedRequestSchema,
  DaemonClientAccessSetPausedResponseSchema,
  DaemonRelayHistoryDeleteRequestSchema,
  DaemonRelayHistoryDeleteResponseSchema,
} from "./client-access/rpc-schemas.js";
import {
  McpChangedMessageSchema,
  McpCreateRequestSchema,
  McpCreateResponseSchema,
  McpDeleteRequestSchema,
  McpDeleteResponseSchema,
  McpListRequestSchema,
  McpListResponseSchema,
  McpTestConnectionRequestSchema,
  McpTestConnectionResponseSchema,
  McpUpdateRequestSchema,
  McpUpdateResponseSchema,
} from "./mcp/rpc-schemas.js";
import {
  MemoryClearRequestSchema,
  MemoryClearResponseSchema,
  MemoryGetStateRequestSchema,
  MemoryGetStateResponseSchema,
  MemoryUpdateStateRequestSchema,
  MemoryUpdateStateResponseSchema,
} from "./memory/rpc-schemas.js";
import {
  SkillChangedMessageSchema,
  SkillCreateRequestSchema,
  SkillCreateResponseSchema,
  SkillDeleteRequestSchema,
  SkillDeleteResponseSchema,
  SkillListRequestSchema,
  SkillListResponseSchema,
  SkillUpdateRequestSchema,
  SkillUpdateResponseSchema,
} from "./skill/rpc-schemas.js";
import {
  TeamChangedMessageSchema,
  TeamCreateRequestSchema,
  TeamCreateResponseSchema,
  TeamDeleteRequestSchema,
  TeamDeleteResponseSchema,
  TeamGetRequestSchema,
  TeamGetResponseSchema,
  TeamListRequestSchema,
  TeamListResponseSchema,
  TeamRunStateRequestSchema,
  TeamRunStateResponseSchema,
  TeamSendRunRequestSchema,
  TeamSendRunResponseSchema,
  TeamUpdateRequestSchema,
  TeamUpdateResponseSchema,
} from "./team/rpc-schemas.js";
import {
  WorkflowCancelRunRequestSchema,
  WorkflowCancelRunResponseSchema,
  WorkflowDeleteRequestSchema,
  WorkflowDeleteResponseSchema,
  WorkflowGetRunRequestSchema,
  WorkflowGetRunResponseSchema,
  WorkflowInspectRequestSchema,
  WorkflowInspectResponseSchema,
  WorkflowListRequestSchema,
  WorkflowListResponseSchema,
  WorkflowRunRequestSchema,
  WorkflowRunResponseSchema,
  WorkflowSaveRequestSchema,
  WorkflowSaveResponseSchema,
} from "./workflow/rpc-schemas.js";

/**
 * Branch-owned RPC registrations live here so the central protocol unions only
 * need one stable spread point when rebasing onto upstream.
 */
export const ExtensionSessionInboundSchemas = [
  AssistantListRequestSchema,
  AssistantCreateRequestSchema,
  AssistantUpdateRequestSchema,
  AssistantDeleteRequestSchema,
  MemoryGetStateRequestSchema,
  MemoryUpdateStateRequestSchema,
  MemoryClearRequestSchema,
  LarkChannelGetStatusRequestSchema,
  LarkChannelApplyBotRequestSchema,
  LarkChannelGetBotApplicationRequestSchema,
  LarkChannelConfigureRequestSchema,
  LarkChannelDeleteBotRequestSchema,
  LarkChannelTestConnectionRequestSchema,
  LarkChannelSetEnabledRequestSchema,
  LarkChannelApprovePairingRequestSchema,
  LarkChannelRejectPairingRequestSchema,
  LarkChannelRevokeUserRequestSchema,
  DaemonClientAccessListRequestSchema,
  DaemonClientAccessApproveRequestSchema,
  DaemonClientAccessSetPausedRequestSchema,
  DaemonClientAccessDeleteRequestSchema,
  DaemonClientAccessHistoryDeleteRequestSchema,
  DaemonRelayHistoryDeleteRequestSchema,
  WorkflowListRequestSchema,
  WorkflowInspectRequestSchema,
  WorkflowRunRequestSchema,
  WorkflowGetRunRequestSchema,
  WorkflowCancelRunRequestSchema,
  WorkflowSaveRequestSchema,
  WorkflowDeleteRequestSchema,
  TeamListRequestSchema,
  TeamCreateRequestSchema,
  TeamUpdateRequestSchema,
  TeamDeleteRequestSchema,
  TeamGetRequestSchema,
  TeamSendRunRequestSchema,
  TeamRunStateRequestSchema,
  McpListRequestSchema,
  McpCreateRequestSchema,
  McpUpdateRequestSchema,
  McpDeleteRequestSchema,
  McpTestConnectionRequestSchema,
  SkillListRequestSchema,
  SkillCreateRequestSchema,
  SkillUpdateRequestSchema,
  SkillDeleteRequestSchema,
] as const;

export const ExtensionSessionOutboundSchemas = [
  AssistantListResponseSchema,
  AssistantCreateResponseSchema,
  AssistantUpdateResponseSchema,
  AssistantDeleteResponseSchema,
  AssistantChangedMessageSchema,
  MemoryGetStateResponseSchema,
  MemoryUpdateStateResponseSchema,
  MemoryClearResponseSchema,
  LarkChannelGetStatusResponseSchema,
  LarkChannelApplyBotResponseSchema,
  LarkChannelGetBotApplicationResponseSchema,
  LarkChannelConfigureResponseSchema,
  LarkChannelDeleteBotResponseSchema,
  LarkChannelTestConnectionResponseSchema,
  LarkChannelSetEnabledResponseSchema,
  LarkChannelApprovePairingResponseSchema,
  LarkChannelRejectPairingResponseSchema,
  LarkChannelRevokeUserResponseSchema,
  LarkChannelStatusChangedMessageSchema,
  DaemonClientAccessListResponseSchema,
  DaemonClientAccessApproveResponseSchema,
  DaemonClientAccessSetPausedResponseSchema,
  DaemonClientAccessDeleteResponseSchema,
  DaemonClientAccessHistoryDeleteResponseSchema,
  DaemonRelayHistoryDeleteResponseSchema,
  WorkflowListResponseSchema,
  WorkflowInspectResponseSchema,
  WorkflowRunResponseSchema,
  WorkflowGetRunResponseSchema,
  WorkflowCancelRunResponseSchema,
  WorkflowSaveResponseSchema,
  WorkflowDeleteResponseSchema,
  TeamListResponseSchema,
  TeamCreateResponseSchema,
  TeamUpdateResponseSchema,
  TeamDeleteResponseSchema,
  TeamGetResponseSchema,
  TeamChangedMessageSchema,
  TeamSendRunResponseSchema,
  TeamRunStateResponseSchema,
  McpListResponseSchema,
  McpCreateResponseSchema,
  McpUpdateResponseSchema,
  McpDeleteResponseSchema,
  McpTestConnectionResponseSchema,
  McpChangedMessageSchema,
  SkillListResponseSchema,
  SkillCreateResponseSchema,
  SkillUpdateResponseSchema,
  SkillDeleteResponseSchema,
  SkillChangedMessageSchema,
] as const;
